name: docker-build-push

on:
  workflow_dispatch:

env:
  REPO_NAME: taggedme/public
  TAGS_NAME: alpine-3.20.3
  CTXS_NAME: .

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:${{ env.CTXS_NAME }}"
          push: true
          tags: ${{ env.REPO_NAME }}/${{ env.TAGS_NAME }}
