name: docker-build-push

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:${{ vars.CTXS_NAME }}"
          push: true
          tags: ${{ vars.REPO_NAME }}/${{ vars.TAGS_NAME }}
