name: docker-build-push

on:
  workflow_dispatch:
    inputs:
      ctxs:
        description: 'Dockerfile dir'
        type: string
        required: true
      tags:
        description: 'docker tags'
        required: true
        type: string
      repo:
        description: 'docker repo'
        type: string
        required: true
      repository:
        type: string
        required: true
      ref:
        type: string
        required: true


env:
  CTXS_NAME: ${{ inputs.ctxs }}
  REPO_NAME: ${{ inputs.repo }}
  TAGS_NAME: ${{ inputs.tags }}

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      - 
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:${{ env.CTXS_NAME }}"
          push: true
          tags: ${{ env.REPO_NAME }}:${{ env.TAGS_NAME }}
